-- local status_ok, bufferline = pcall(require, "bufferline")
-- if not status_ok then
-- 	vim.notify("Failed loading " .. req_file, vim.log.levels.ERROR)
-- 	return
-- end
--
-- bufferline.setup({
-- 	options = {
-- 		close_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
-- 		right_mouse_command = "Bdelete! %d", -- can be a string | function, see "Mouse actions"
-- 		offsets = {
-- 			{ filetype = "NvimTree", text = "", padding = 1 },
-- 			{ filetype = "Outline", text = "", padding = 1 },
-- 		},
-- 		indicator = {
-- 			icon = "",
-- 			style = "underline",
-- 		},
-- 		separator_style = { "", "" }, -- { '', '' }, -- | "thick" | "thin" | { 'any', 'any' },
-- 		modified_icon = "",
-- 		max_prefix_length = 13,
-- 		max_name_length = 14,
-- 		tab_size = 20,
-- 		color_icons = true,
-- 		diagnostics = "nvim_lsp",
-- 	},
-- 	highlights = {
-- 		fill = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		background = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		tab = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		tab_selected = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		tab_close = {
-- 			fg = "Red",
-- 			bg = "Black",
-- 		},
-- 		close_button = {
-- 			fg = "Red",
-- 			bg = "Black",
-- 		},
-- 		close_button_visible = {
-- 			fg = "Red",
-- 			bg = "Black",
-- 		},
-- 		close_button_selected = {
-- 			fg = "Red",
-- 			bg = "Black",
-- 		},
-- 		--
-- 		buffer_visible = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		buffer_selected = {
-- 			fg = "White",
-- 			bg = "Black",
-- 			bold = true,
-- 		},
-- 		numbers = {
-- 			fg = "Grey",
-- 			bg = "Black",
-- 		},
-- 		numbers_visible = {
-- 			fg = "Grey",
-- 			bg = "Black",
-- 		},
-- 		number_selected = {
-- 			fg = "Grey",
-- 			bg = "Black",
-- 			bold = true,
-- 		},
-- 		--
-- 		diagnostic = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		diagnostic_visible = {
-- 			fg = "White",
-- 			bg = "Black",
-- 		},
-- 		diagnostic_selected = {
-- 			fg = "White",
-- 			bg = "Black",
-- 			bold = true,
-- 			italic = true,
-- 		},
-- 	},
-- })
